name: dotted
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.3.4
  envied: ^0.5.3
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.9.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.8
  drift_dev: ^2.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/
