name: dotted
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # OAuth Providers
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  # Database
  supabase_flutter: ^2.5.3

  # State Management
  flutter_bloc: ^8.1.5

  # Widgets
  lottie: ^3.1.2
  icons_plus: ^5.0.0
  google_maps_flutter: ^2.6.1
  calendar_date_picker2: ^1.0.2
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  timeline_tile: ^2.0.0

  # Utils
  collection: ^1.18.0
  meta: ^1.12.0
  equatable: ^2.0.5
  http: ^1.2.1
  intl: ^0.19.0
  csv: ^6.0.0
  flutter_config: ^2.0.2
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0
  crypto: ^3.0.3
  flutter_animate: ^4.5.0
  dartz: ^0.10.1

  # SQLlite for local storage
  sqlite3: ^2.4.3
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.10
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/world_cities.db
    - assets/lottie/
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/dotted_earth.png"
  min_sdk_android: 21
  remove_alpha_ios: true
